// Alle Bilder liegen direkt im Ordner images/.
// Kategorie, Name und Anime werden ausschließlich hier gepflegt.
// level: "easy", "medium" oder "hard".
const CHARACTERS = [
    {
        name: "Grell",
        anime: "Black Butler",
        level: "medium",
        image: "images/grell.webp",
    },
    {
        name: "Hisoka",
        anime: "Hunter x Hunter",
        level: "easy",
        image: "images/hisoka.png",
    },
    {
        name: "Hin",
        anime: "Howls moving Castle",
        level: "hard",
        image: "images/hin.png",
    },
    {
        name: "Mononoke & Moro",
        anime: "Mononoke Hime",
        level: "medium",
        image: "images/mononoke.png",
    },
    {
        name: "Pikachu",
        anime: "Pokémon",
        level: "easy",
        image: "images/pikachu.jpeg",
    },
    {
        name: "Monkey D. Luffy",
        anime: "One Piece",
        level: "easy",
        image: "images/ruffy.jpeg",
    },
    {
        name: "Naruto Uzumaki",
        anime: "Naruto",
        level: "easy",
        image: "images/naruto.jpeg",
    },
    {
        name: "Son Goku",
        anime: "Dragon Ball",
        level: "easy",
        image: "images/son_goku.jpeg",
    },
    {
        name: "Sailor Moon",
        anime: "Sailor Moon",
        level: "easy",
        image: "images/sailor_moon.jpeg",
    },
    {
        name: "Anya Forger",
        anime: "Spy × Family",
        level: "easy",
        image: "images/anya.jpeg",
    },
    {
        name: "Satoru Gojo",
        anime: "Jujutsu Kaisen",
        level: "easy",
        image: "images/gojo.jpeg",
    },
    {
        name: "Tanjiro Kamado",
        anime: "Demon Slayer",
        level: "easy",
        image: "images/tanjiro.jpeg",
    },
    {
        name: "Eren Jäger (Titan)",
        anime: "Attack on Titan",
        level: "easy",
        image: "images/eren.jpeg",
    },
    {
        name: "Frieren",
        anime: "Frieren",
        level: "medium",
        image: "images/frieren.jpeg",
    },
    {
        name: "Power",
        anime: "Chainsaw Man",
        level: "medium",
        image: "images/power.jpeg",
    },
    {
        name: "Maomao",
        anime: "The Apothecary Diaries",
        level: "medium",
        image: "images/maomao.jpeg",
    },
    {
        name: "Kyojuro Rengoku",
        anime: "Demon Slayer",
        level: "medium",
        image: "images/rengoku.jpeg",
    },
    {
        name: "Reigen Arataka",
        anime: "Mob Psycho 100",
        level: "medium",
        image: "images/reigen.jpeg",
    },
    {
        name: "Okarun (verwandelt)",
        anime: "Dandadan",
        level: "medium",
        image: "images/okarun.jpeg",
    },
    {
        name: "Levi Ackerman",
        anime: "Attack on Titan",
        level: "medium",
        image: "images/levi.jpeg",
    },
    {
        name: "Ryuk",
        anime: "Death Note",
        level: "medium",
        image: "images/ryuk.jpeg",
    },
    {
        name: "Mikasa Ackerman",
        anime: "Attack on Titan",
        level: "medium",
        image: "images/mikasa.jpeg",
    },
    {
        name: "Kishibe",
        anime: "Chainsaw Man",
        level: "hard",
        image: "images/kishibe.jpeg",
    },
    {
        name: "Mechamaru",
        anime: "Jujutsu Kaisen",
        level: "hard",
        image: "images/mechamaru.jpeg",
    },
    {
        name: "Fern",
        anime: "Frieren",
        level: "hard",
        image: "images/fern.jpeg",
    },
    {
        name: "Shizuku Murasaki",
        anime: "Hunter × Hunter",
        level: "hard",
        image: "images/shizuku.jpeg",
    },
    {
        name: "Mumen Rider",
        anime: "One Punch Man",
        level: "hard",
        image: "images/mumen_rider.jpeg",
    },
    {
        name: "Gabi Braun",
        anime: "Attack on Titan",
        level: "hard",
        image: "images/gabi.jpeg",
    },
    {
        name: "Pieck Finger",
        anime: "Attack on Titan",
        level: "hard",
        image: "images/pieck.webp",
    },
    {
        name: "Suguru Geto",
        anime: "Jujutsu Kaisen",
        level: "hard",
        image: "images/geto.jpeg",
    },
];
